### PR TITLE
Compile with LLVM v9.0.1

### PR DESCRIPTION
**Pull request by kunaltyagi**
I made a few changes to get IWYU to get compiled with LLVM 9.0.1 (the latest shipped version on arch).

I tried to build using `-DCMAKE_PREFIX_PATH` but it was ignored so I went ahead and made the changes to compile against just v9.0.1

### CODE REVIEW

**Comment by kimgr** [comment]
I see our docs (https://github.com/include-what-you-use/include-what-you-use/blob/master/README.md#how-to-build) are misleading. We don't take version-specific patches for master -- it follows Clang and LLVM's master.

Any LLVM 9 patches should go onto our `clang_9.0` branch. Unfortunately I haven't had a chance to create it yet -- I wanted to include the IWYU improvements but exclude the Clang compatibility changes.

I'll come around to it at some point soon.

**Comment by kimgr** [comment]
Docs are updated to be less confusing now.

**Comment by kunaltyagi** [comment]
> We don't take version-specific patches for master -- it follows Clang and LLVM's master

LLVM master is now 10.x which is not what the master branch of iwyu

**Comment by kimgr** [comment]
It should be. What are you seeing that contradicts it?

**Comment by kunaltyagi** [comment]
> What are you seeing that contradicts it?

The include paths during compilation error. There isn't any custom path. And the linker errors point to compilation using the system paths instead of the custom built llvm

I used `cmake -GNinja -DCMAKE_PREFIX_PATH=<build_tree_of_llvm> <location of iwyu> && ninja`

**Comment by kimgr** [comment]
That's odd. I think I use the same thing without issue.

On my machine:

* LLVM monorepo checkout in .../llvm-project
* LLVM build tree in .../llvm-project/out/master
* IWYU checkout in .../iwyu/include-what-you-use
* IWYU build tree in .../iwyu/out/master

My CMake invocation is usually:

    $ cd .../iwyu/out/master
    $ cmake -GNinja -DCMAKE_PREFIX_PATH .../llvm-project/out/master ../../include-what-you-use

I haven't done this in a while, but it should work. Are you sure you have `master` checked out and built on the LLVM side? Also, do you build the `clang` target on the LLVM side to make sure it's all there?

**Comment by kunaltyagi** [comment]
Thanks for the help. My setup is very similar (I replicated the steps to make sure). It might be a weird corner case that I'm the victim of.
```
$ cd $ROOT/llvm-project
$ basename $PWD && git branch
llvm-project
* master
  release/9.x
$ git log -n 1
commit 4a5df7312ec2c14360e4e12596a1ef63be39a480
---
$ cd $ROOT/build/llvm-plain/
$ cmake -GNinja -DLLVM_ENABLE_PROJECTS=clang $ROOT/llvm-project/llvm/ && ninja
---
$ cd $ROOT/build/iwyu
$ cmake -GNinja -DCMAKE_PREFIX_PATH=../llvm-plain/ $ROOT/include-what-you-use/ && ninja
```

I use arch, so my system llvm isn't master, but I didn't expect to face compilation errors since llvm master is also on 9 (though internal API is expected to change, which is why I created the PR)
```
$ yay -Q llvm
llvm 9.0.0-3
```

**Comment by kimgr** [comment]
LLVM master is no longer on 9, it's on 10.

**Comment by kimgr** [comment]
... and all the breaking changes happened after they took the 9 branch.

**Comment by kunaltyagi** [comment]
Dang. Thanks for your help. 😃

Should I create a new PR for 9.0 branch? Or is this sufficient for the future branch that you've alluded to?

**Comment by kimgr** [comment]
Glad it got sorted :)

I'll figure something out myself for the 9.0 branch. Not sure yet if I want to make it a clean cut, or backport IWYU-side improvements, or revert compatibility fixes on the branch.
