### ISSUE TITLE
Build error with clang 17: ‘None’ is not a member of ‘clang::ElaboratedTypeKeyword’

### ISSUE THREAD

**Issue by rustyx** [include-what-you-use/include-what-you-use#1521]
master is failing to build on Ubuntu 23.10 using clang version 17.0.2:

```none
[build] iwyu_ast_util.cc:278:66: error: ‘None’ is not a member of ‘clang::ElaboratedTypeKeyword’
[build]   278 |          elaborated_type->getKeyword() != ElaboratedTypeKeyword::None;
[build]       |                                                                  ^~~~
```

It seems like with clang 17 `ElaboratedTypeKeyword::None` should be `ElaboratedTypeKeyword::ETK_None`.

Is there a pattern in this project for handling these types of clang version-specific quirks? If so, I could perhaps open a PR with a fix.

**Comment by kimgr** [comment]
@rustyx Yeah, the pattern is "use the right branch" :) -- https://github.com/include-what-you-use/include-what-you-use?tab=readme-ov-file#clang-compatibility

**Comment by kimgr** [comment]
I don't think there's much more to do here, so I'll close the issue. @rustyx Please reopen if you need something else.

**Comment by rustyx** [comment]
Ok thanks for the info. Wouldn't it be an idea to use preprocessor flags (feature flags) instead of separate branches for at least the most recent clang versions (like 14...18)? Or are the differences still too great? It'd be nice to have all the latest features when they land in master, while still using clang 17.

**Comment by kimgr** [comment]
There's some discussion here on the kinds of issues we have seen so far: https://github.com/include-what-you-use/include-what-you-use/issues/1498.

I'd much rather focus what little time I have for IWYU on its actual core problem space.
