### ISSUE TITLE
`fatal error: 'stdarg.h' file not found` when bumping llvm to 21.1.2

### ISSUE THREAD

**Issue by chenrui333** [include-what-you-use/include-what-you-use#1825]
👋 seeing the following regression test failure when bumping llvm to 21.1.2

```
  ==> /opt/homebrew/Cellar/include-what-you-use/0.25/bin/include-what-you-use main.cc -Xiwyu --mapping_file=/opt/homebrew/opt/llvm/include/c++/v1/libcxx.imp 2>&1
  In file included from main.cc:1:
  In file included from /opt/homebrew/Cellar/include-what-you-use/0.25/libexec/bin/../include/c++/v1/iostream:45:
  In file included from /opt/homebrew/Cellar/include-what-you-use/0.25/libexec/bin/../include/c++/v1/ios:228:
  In file included from /opt/homebrew/Cellar/include-what-you-use/0.25/libexec/bin/../include/c++/v1/__locale:17:
  In file included from /opt/homebrew/Cellar/include-what-you-use/0.25/libexec/bin/../include/c++/v1/__locale_dir/locale_base_api.h:115:
  In file included from /opt/homebrew/Cellar/include-what-you-use/0.25/libexec/bin/../include/c++/v1/__locale_dir/support/apple.h:18:
  In file included from /opt/homebrew/Cellar/include-what-you-use/0.25/libexec/bin/../include/c++/v1/__locale_dir/support/bsd_like.h:23:
  In file included from /opt/homebrew/Cellar/include-what-you-use/0.25/libexec/bin/../include/c++/v1/wchar.h:116:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX26.sdk/usr/include/wchar.h:67:
  /Library/Developer/CommandLineTools/SDKs/MacOSX26.sdk/usr/include/_wchar.h:90:10: fatal error: 'stdarg.h' file not found
     90 | #include <stdarg.h>
        |          ^~~~~~~~~~
```

relates to https://github.com/Homebrew/homebrew-core/pull/245468

**Comment by kimgr** [comment]
You're somehow missing the compiler builtin headers. It's surprising that this would break from a minor llvm upgrade.

See https://github.com/include-what-you-use/include-what-you-use/?tab=readme-ov-file#how-to-install for the long backstory.

You can troubleshoot by running: `include-what-you-use -print-resource-dir` and see if that path exists (probably not).

Have you configured `IWYU_RESOURCE_DIR` and `IWYU_RESOURCE_RELATIVE_TO` in any interesting way, or are they at defaults?

**Comment by chenrui333** [comment]
the rebuild seems resolved the issue on our end. :)
