### ISSUE TITLE
LLVM/Clang 7.0 is out

### ISSUE THREAD

**Issue by apaprocki** [include-what-you-use/include-what-you-use#592]
Can a new release be cut to work with the new major version? Thanks

**Comment by kimgr** [comment]
We have a few significant improvements I would like to get into the IWYU for 7.0, so it will probably be a little longer. But hopefully I can make up some time to work on it soon.

**Comment by springmeyer** [comment]
I tried building against llvm 7.0.0 with https://github.com/include-what-you-use/include-what-you-use/commit/569a7ee144d756cd01a533913ed3ee2c78d99f0f and hit:


```
../tools/clang/tools/include-what-you-use/iwyu.cc:2056:19: error: no member named 'CK_ZeroToOCLOpaqueType' in namespace 'clang'; did you mean 'CK_ZeroToOCLQueue'?
      case clang::CK_ZeroToOCLOpaqueType: // OpenCL opaque types are built-in.
           ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
                  CK_ZeroToOCLQueue
../tools/clang/include/clang/AST/OperationKinds.def:325:1: note: 'CK_ZeroToOCLQueue' declared here
CAST_OPERATION(ZeroToOCLQueue)
^
../tools/clang/include/clang/AST/OperationKinds.h:22:30: note: expanded from macro 'CAST_OPERATION'
#define CAST_OPERATION(Name) CK_##Name,
                             ^
<scratch space>:25:1: note: expanded from here
CK_ZeroToOCLQueue
^
../tools/clang/tools/include-what-you-use/iwyu.cc:2066:19: error: no member named 'CK_FixedPointCast' in namespace 'clang'
      case clang::CK_FixedPointCast:
           ~~~~~~~^
../tools/clang/tools/include-what-you-use/iwyu.cc:2067:19: error: no member named 'CK_FixedPointToBoolean' in namespace 'clang'
      case clang::CK_FixedPointToBoolean:
           ~~~~~~~^
../tools/clang/tools/include-what-you-use/iwyu.cc:2045:13: warning: enumeration value 'CK_ZeroToOCLEvent' not handled in switch [-Wswitch]
    switch (expr->getCastKind()) {
            ^
../tools/clang/tools/include-what-you-use/iwyu.cc:2045:13: warning: enumeration value 'CK_ZeroToOCLEvent' not handled in switch [-Wswitch]
../tools/clang/tools/include-what-you-use/iwyu.cc:2045:13: warning: enumeration value 'CK_ZeroToOCLEvent' not handled in switch [-Wswitch]
```

**Comment by kimgr** [comment]
Yes, I just test-built a branch from HEAD~2 yesterday, and it works. I just didn't get a chance to push it. Look out for `clang_7.0` in the near future.

**Comment by kimgr** [comment]
`clang_7.0` is pushed: https://github.com/include-what-you-use/include-what-you-use/tree/clang_7.0

I'm planning to backport whatever we can finish in a reasonable timeframe before we package up a release.

**Comment by jonesmz** [comment]
@kimgr Do you happen to have a list of known issues with the clang_7.0 branch ?

**Comment by kimgr** [comment]
@jonesmz Not really. All open issues and pull requests are still open for clang_7.0, otherwise I think it's up to date.

**Comment by jonesmz** [comment]
I tried to find clang_7.0 issues, and was not able to identify any easily.

The milestone for IWYU 11 seems to be 100% complete.

I'm asking about the issues because I'm working on getting the clang_7.0 branch to talk to my code, and wanted to know if I was going to run into problems.

That being said, could you explain how I can find the list of open issues / PRs for the clang_7.0 branch? Perhaps I'm not as good at Github as I thought.

**Comment by jonesmz** [comment]
> We don't track issues branch-by-branch, so all open issues apply to most branches (barring regressions).

That's very difficult for third parties to easily understand (one way or another) by looking at the github repository. 

> > and wanted to know if I was going to run into problems.
>
> Almost certainly :). IWYU is a tractable but difficult problem, so you probably won't agree with all of IWYU's suggestions (and some will be flat out wrong).

Right, I should have clarified my statement. I meant "Run into problems like the code can't even compile, or it's known to give results that are dangerous due to bug #xyz which we plan to fix before releasing a Clang 7 compatible version." 

Obviously all software has some issues, no matter the quality :-)

> I was hoping to pack as many fixes as possible into IWYU 0.11, but I guess we should ship 0.11 before Clang 8 starts its release cycle. I'll see if I can find some chunk of time to backport relevant fixes from master and package up a release.

Ok. Thank you for the explanation, and the work you do on IWYU.

**Comment by kimgr** [comment]
IWYU 0.11 based on Clang 7 is now live and should be available from

- GitHub: https://github.com/include-what-you-use/include-what-you-use/releases/tag/0.11
- include-what-you-use.org: https://include-what-you-use.org/

Thanks to all contributors!
