### ISSUE TITLE
IWYU doesn't work with MSVC 2019 version 16.8.x

### ISSUE THREAD

**Issue by Markus43** [include-what-you-use/include-what-you-use#872]
See here: https://github.com/microsoft/STL/issues/1300

The linked Microsoft issue also contains a patch to intrin0,h (in my case it's C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\intrin0.h) which can be used as a workaround - after applying this patch, iwyu works again.

MSVC 16.9 will fix this issue. I suggest to keep this issue open as a reference until 16.9 is released.

The error message is something like:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29304\include\intrin.h(56,1): error G7973E533: expected function body after function declarator [clang-diagnostic-error]
__MACHINE(void * _AddressOfReturnAddress(void))
```

**Comment by kimgr** [comment]
Thanks for the heads-up and workaround instructions, much appreciated!
