### ISSUE TITLE
Cannot link iwyu on clang 3.7

### ISSUE THREAD

**Issue by apollo13** [include-what-you-use/include-what-you-use#258]
I am on the 3.7 branch and getting the following linker error:
```
make                                                                                                                                                                                
[  7%] Linking CXX executable include-what-you-use
Debian clang version 3.7.1-1 (tags/RELEASE_371/final) (based on LLVM 3.7.1)
Target: x86_64-pc-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/bin/../lib/gcc/i586-linux-gnu/4.8
Found candidate GCC installation: /usr/bin/../lib/gcc/i586-linux-gnu/4.8.5
Found candidate GCC installation: /usr/bin/../lib/gcc/i586-linux-gnu/4.9
Found candidate GCC installation: /usr/bin/../lib/gcc/i586-linux-gnu/4.9.3
Found candidate GCC installation: /usr/bin/../lib/gcc/i586-linux-gnu/5.3.1
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.3.1
Found candidate GCC installation: /usr/lib/gcc/i586-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/i586-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/i586-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i586-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/i586-linux-gnu/5.3.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.3.1
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.3.1
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/usr/bin/ld" -export-dynamic --hash-style=both --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o include-what-you-use /usr/bin/../lib/gcc/x86_64-linux-gnu/5.3.1/../../../x86_64-linux-gnu/crt1.o /usr/bin/../lib/gcc/x86_64-linux-gnu/5.3.1/../../../x86_64-linux-gnu/crti.o /usr/bin/../lib/gcc/x86_64-linux-gnu/5.3.1/crtbegin.o -L/usr/bin/../lib/gcc/x86_64-linux-gnu/5.3.1 -L/usr/bin/../lib/gcc/x86_64-linux-gnu/5.3.1/../../../x86_64-linux-gnu -L/usr/bin/../lib/gcc/x86_64-linux-gnu/5.3.1/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/usr/lib/x86_64-linux-gnu/../../lib64 -L/usr/bin/../lib/gcc/x86_64-linux-gnu/5.3.1/../../.. -L/usr/lib/llvm-3.7/bin/../lib -L/lib -L/usr/lib CMakeFiles/include-what-you-use.dir/iwyu.cc.o CMakeFiles/include-what-you-use.dir/iwyu_ast_util.cc.o CMakeFiles/include-what-you-use.dir/iwyu_cache.cc.o CMakeFiles/include-what-you-use.dir/iwyu_driver.cc.o CMakeFiles/include-what-you-use.dir/iwyu_getopt.cc.o CMakeFiles/include-what-you-use.dir/iwyu_globals.cc.o CMakeFiles/include-what-you-use.dir/iwyu_include_picker.cc.o CMakeFiles/include-what-you-use.dir/iwyu_lexer_utils.cc.o CMakeFiles/include-what-you-use.dir/iwyu_location_util.cc.o CMakeFiles/include-what-you-use.dir/iwyu_output.cc.o CMakeFiles/include-what-you-use.dir/iwyu_path_util.cc.o CMakeFiles/include-what-you-use.dir/iwyu_preprocessor.cc.o CMakeFiles/include-what-you-use.dir/iwyu_verrs.cc.o -lclangFrontend -lclangSerialization -lclangDriver -lclangParse -lclangSema -lclangAnalysis -lclangAST -lclangBasic -lclangEdit -lclangLex -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMX86Desc -lLLVMX86AsmPrinter -lLLVMX86Info -lLLVMX86Utils -lLLVMCodeGen -lLLVMipo -lLLVMScalarOpts -lLLVMInstCombine -lLLVMTransformUtils -lLLVMipa -lLLVMTarget -lLLVMAnalysis -lLLVMOption -lLLVMMCDisassembler -lLLVMMCParser -lLLVMMC -lLLVMObject -lLLVMBitReader -lLLVMCore -lLLVMSupport -lpthread -lz -lcurses -lform -ldl -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/bin/../lib/gcc/x86_64-linux-gnu/5.3.1/crtend.o /usr/bin/../lib/gcc/x86_64-linux-gnu/5.3.1/../../../x86_64-linux-gnu/crtn.o
CMakeFiles/include-what-you-use.dir/iwyu.cc.o: In function `include_what_you_use::IwyuBaseAstVisitor<include_what_you_use::IwyuAstConsumer>::ReportDeclUseWithComment(clang::SourceLocation, clang::NamedDecl const*, char const*)':
/home/florian/sources/include-what-you-use/iwyu.cc:(.text._ZN20include_what_you_use18IwyuBaseAstVisitorINS_15IwyuAstConsumerEE24ReportDeclUseWithCommentEN5clang14SourceLocationEPKNS3_9NamedDeclEPKc[_ZN20include_what_you_use18IwyuBaseAstVisitorINS_15IwyuAstConsumerEE24ReportDeclUseWithCommentEN5clang14SourceLocationEPKNS3_9NamedDeclEPKc]+0x326): undefined reference to `clang::NamedDecl::getQualifiedNameAsString() const'
CMakeFiles/include-what-you-use.dir/iwyu.cc.o: In function `include_what_you_use::IwyuBaseAstVisitor<include_what_you_use::InstantiatedTemplateVisitor>::ReportDeclUseWithComment(clang::SourceLocation, clang::NamedDecl const*, char const*)':
/home/florian/sources/include-what-you-use/iwyu.cc:(.text._ZN20include_what_you_use18IwyuBaseAstVisitorINS_27InstantiatedTemplateVisitorEE24ReportDeclUseWithCommentEN5clang14SourceLocationEPKNS3_9NamedDeclEPKc[_ZN20include_what_you_use18IwyuBaseAstVisitorINS_27InstantiatedTemplateVisitorEE24ReportDeclUseWithCommentEN5clang14SourceLocationEPKNS3_9NamedDeclEPKc]+0x326): undefined reference to `clang::NamedDecl::getQualifiedNameAsString() const'
CMakeFiles/include-what-you-use.dir/iwyu.cc.o: In function `include_what_you_use::IwyuBaseAstVisitor<include_what_you_use::InstantiatedTemplateVisitor>::VisitCXXMethodDecl(clang::CXXMethodDecl*)':
/home/florian/sources/include-what-you-use/iwyu.cc:(.text._ZN20include_what_you_use18IwyuBaseAstVisitorINS_27InstantiatedTemplateVisitorEE18VisitCXXMethodDeclEPN5clang13CXXMethodDeclE[_ZN20include_what_you_use18IwyuBaseAstVisitorINS_27InstantiatedTemplateVisitorEE18VisitCXXMethodDeclEPN5clang13CXXMethodDeclE]+0xba): undefined reference to `clang::NamedDecl::getQualifiedNameAsString() const'
CMakeFiles/include-what-you-use.dir/iwyu.cc.o: In function `include_what_you_use::InstantiatedTemplateVisitor::ReplayUsesFromCache(include_what_you_use::FullUseCache const&, clang::NamedDecl const*, clang::SourceLocation)':
/home/florian/sources/include-what-you-use/iwyu.cc:(.text._ZN20include_what_you_use27InstantiatedTemplateVisitor19ReplayUsesFromCacheERKNS_12FullUseCacheEPKN5clang9NamedDeclENS4_14SourceLocationE[_ZN20include_what_you_use27InstantiatedTemplateVisitor19ReplayUsesFromCacheERKNS_12FullUseCacheEPKN5clang9NamedDeclENS4_14SourceLocationE]+0x86): undefined reference to `clang::NamedDecl::getQualifiedNameAsString() const'
CMakeFiles/include-what-you-use.dir/iwyu.cc.o: In function `include_what_you_use::InstantiatedTemplateVisitor::ReplayClassMemberUsesFromPrecomputedList(clang::TemplateSpecializationType const*)':
/home/florian/sources/include-what-you-use/iwyu.cc:(.text._ZN20include_what_you_use27InstantiatedTemplateVisitor40ReplayClassMemberUsesFromPrecomputedListEPKN5clang26TemplateSpecializationTypeE[_ZN20include_what_you_use27InstantiatedTemplateVisitor40ReplayClassMemberUsesFromPrecomputedListEPKN5clang26TemplateSpecializationTypeE]+0x2c1): undefined reference to `clang::NamedDecl::getQualifiedNameAsString() const'
CMakeFiles/include-what-you-use.dir/iwyu.cc.o:/home/florian/sources/include-what-you-use/iwyu.cc:(.text._ZN20include_what_you_use18IwyuBaseAstVisitorINS_15IwyuAstConsumerEE18VisitCXXMethodDeclEPN5clang13CXXMethodDeclE[_ZN20include_what_you_use18IwyuBaseAstVisitorINS_15IwyuAstConsumerEE18VisitCXXMethodDeclEPN5clang13CXXMethodDeclE]+0xba): more undefined references to `clang::NamedDecl::getQualifiedNameAsString() const' follow
CMakeFiles/include-what-you-use.dir/iwyu_ast_util.cc.o: In function `clang::NamedDecl::getNameAsString() const':
/home/florian/sources/include-what-you-use/iwyu_ast_util.cc:(.text._ZNK5clang9NamedDecl15getNameAsStringEv[_ZNK5clang9NamedDecl15getNameAsStringEv]+0x1c): undefined reference to `clang::DeclarationName::getAsString() const'
CMakeFiles/include-what-you-use.dir/iwyu_ast_util.cc.o: In function `clang::QualType::getAsString(clang::SplitQualType)':
/home/florian/sources/include-what-you-use/iwyu_ast_util.cc:(.text._ZN5clang8QualType11getAsStringENS_13SplitQualTypeE[_ZN5clang8QualType11getAsStringENS_13SplitQualTypeE]+0x24): undefined reference to `clang::QualType::getAsString(clang::Type const*, clang::Qualifiers)'
CMakeFiles/include-what-you-use.dir/iwyu_globals.cc.o: In function `include_what_you_use::PrintVersion()':
/home/florian/sources/include-what-you-use/iwyu_globals.cc:(.text+0x274d): undefined reference to `clang::getClangFullVersion()'
CMakeFiles/include-what-you-use.dir/iwyu_driver.cc.o: In function `include_what_you_use::CreateCompilerInstance(int, char const**)':
/home/florian/sources/include-what-you-use/iwyu_driver.cc:(.text+0x192): undefined reference to `llvm::sys::getDefaultTargetTriple()'
/home/florian/sources/include-what-you-use/iwyu_driver.cc:(.text+0xbba): undefined reference to `clang::CompilerInvocation::GetResourcesPath(char const*, void*)'
CMakeFiles/include-what-you-use.dir/iwyu_driver.cc.o: In function `include_what_you_use::(anonymous namespace)::GetExecutablePath(char const*)':
/home/florian/sources/include-what-you-use/iwyu_driver.cc:(.text+0xd3a): undefined reference to `llvm::sys::fs::getMainExecutable(char const*, void*)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/include-what-you-use.dir/build.make:408: recipe for target 'include-what-you-use' failed
make[2]: *** [include-what-you-use] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/include-what-you-use.dir/all' failed
make[1]: *** [CMakeFiles/include-what-you-use.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Any ideas?

**Comment by kimgr** [comment]
I haven't had time to double-check that the clang_3.7 still builds with LLVM/Clang's 3.7 branch, but they seem to generally keep it API-stable in minor releases, so I'd be surprised if it doesn't.

Can you list the exact steps you took to get to this link error? Which LLVM/Clang version you checked out/have in your /usr tree? Which IWYU branch you checked out? Your exact CMake command?

Thanks.

**Comment by apollo13** [comment]
I am on 98f3e62d371ae602061951115efc3b75ff255824 of clang_3.7.
```
clang++-3.7 --version
Debian clang version 3.7.1-1 (tags/RELEASE_371/final) (based on LLVM 3.7.1)
Target: x86_64-pc-linux-gnu
Thread model: posix
```
cmake:
```
cmake -G "Unix Makefiles" -DIWYU_LLVM_ROOT_PATH=/usr/lib/llvm-3.7 -DCMAKE_CXX_COMPILER=clang++-3.7 -DCMAKE_C_COMPILER=clang-3.7 -DCMAKE_EXE_LINKER_FLAGS=-v ../include-what-you-use 
-- The C compiler identification is Clang 3.7.1
-- The CXX compiler identification is Clang 3.7.1
-- Check for working C compiler: /usr/bin/clang-3.7
-- Check for working C compiler: /usr/bin/clang-3.7 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++-3.7
-- Check for working CXX compiler: /usr/bin/clang++-3.7 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- IWYU out-of-tree configuration
-- Found Git: /usr/bin/git (found version "2.7.0") 
-- Found Curses: /usr/lib/x86_64-linux-gnu/libcurses.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/florian/sources/include-what-you-use-build
```

**Comment by kimgr** [comment]
I just built the IWYU `clang_3.7` branch against a source checkout of the `RELEASE_371/final` tag without issue.

The link error you're seeing seems to indicate `NamedDecl::getQualifiedNameAsString` doesn't exist, and that just seems weird. It's been there forever, and it's still there in my RELEASE_371 checkout.

I wonder if you're getting the right libraries on the link line... Can you double-check if you have the `libclangAST.a` library somewhere in your `/usr/lib` tree?

**Comment by apollo13** [comment]
It is there as `/usr/lib/llvm-3.7/lib/libclangAST.a`. nm says:
```
➜  lib  nm /usr/lib/llvm-3.7/lib/libclangAST.a  --demangle|grep getQualifiedNameAsString
                 U clang::NamedDecl::getQualifiedNameAsString[abi:cxx11]() const
0000000000000000 T clang::NamedDecl::getQualifiedNameAsString[abi:cxx11]() const
                 U clang::NamedDecl::getQualifiedNameAsString[abi:cxx11]() const
```

**Comment by kimgr** [comment]
I'm out of ideas, sorry.

**Comment by apollo13** [comment]
I think I am running into:
https://llvm.org/bugs/show_bug.cgi?id=23529
and https://gcc.gnu.org/ml/gcc-patches/2015-04/msg00153.html

**Comment by kimgr** [comment]
Ugh, that looks like a mess of epic proportions. But then the answer should be to use GCC instead of Clang to build IWYU.

**Comment by apollo13** [comment]
Yupp, building then works, I am getting errors about a missing `stddef.h` when running it against my project now, but I hope I can figure that out:
```
include-what-you-use -c -pipe -O2 -D_REENTRANT -Wall -W -fPIC -DQT_NO_DEBUG -DQT_WEBKITWIDGETS_LIB -DQT_WEBKIT_LIB -DQT_PRINTSUPPORT_LIB -DQT_HELP_LIB -DQT_UITOOLS_LIB -DQT_UIPLUGIN_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SCRIPT_LIB -DQT_CORE_LIB -I. -Isrc -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebKitWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebKit -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtHelp -isystem /usr/include/x86_64-linux-gnu/qt5/QtUiTools -isystem /usr/include/x86_64-linux-gnu/qt5/QtUiPlugin -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtScript -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Irelease -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o release/actionkey.o src/actionkey.cpp
In file included from src/actionkey.cpp:20:
In file included from src/actionkey.h:23:
In file included from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QAction:1:
In file included from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qaction.h:37:
In file included from /usr/include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h:37:
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h:37:
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:39:
/usr/lib/gcc/x86_64-linux-gnu/5.3.1/../../../../include/c++/5.3.1/cstddef:45:10: fatal error: 'stddef.h' file not found
#include <stddef.h>
         ^
```

**Comment by apollo13** [comment]
Okay, just as a note for everyone else trying this on a system with GCC 5:
 * Compile using GCC, do not try to use clang!
 * Copy/Symlink the resulting binary to /usr/lib/llvm-3.7/bin/ -- otherwise includes will not get found properly.

**Comment by kimgr** [comment]
Thanks for the good info!

The builtin header problem is documented at https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/InstructionsForUsers.md#how-to-install. If you don't want to install the `include-what-you-use` binary into your `/usr` tree, you can also copy the headers out next to the binary.
