### ISSUE TITLE
Linking segfault with 7.0

### ISSUE THREAD

**Issue by peroket** [include-what-you-use/include-what-you-use#645]
When trying to compile iwyu 7.0 for clang 7.0, the compilation goes fine but the linking segfaults. LLVM dependencies are installed via apt-get on Ubuntu 16.04. It happens when compiling with clang itself or gcc. Cmake is 3.13.2. I tried with a different version of cmake (3.5.1) but the same thing happens.

Can you help me?

Example:
```
$ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/lib/llvm-7 ..
-- IWYU: out-of-tree configuration
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Linker detection: GNU ld
-- Performing Test C_SUPPORTS_FPIC
-- Performing Test C_SUPPORTS_FPIC - Success
-- Performing Test CXX_SUPPORTS_FPIC
-- Performing Test CXX_SUPPORTS_FPIC - Success
-- Building with -fPIC
-- Performing Test SUPPORTS_FVISIBILITY_INLINES_HIDDEN_FLAG
-- Performing Test SUPPORTS_FVISIBILITY_INLINES_HIDDEN_FLAG - Success
-- Performing Test C_SUPPORTS_WERROR_DATE_TIME
-- Performing Test C_SUPPORTS_WERROR_DATE_TIME - Success
-- Performing Test CXX_SUPPORTS_WERROR_DATE_TIME
-- Performing Test CXX_SUPPORTS_WERROR_DATE_TIME - Success
-- Performing Test C_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW
-- Performing Test C_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW - Failed
-- Performing Test CXX_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW
-- Performing Test CXX_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW - Failed
-- Performing Test CXX_SUPPORTS_CXX11
-- Performing Test CXX_SUPPORTS_CXX11 - Success
-- Performing Test C_SUPPORTS_FNO_FUNCTION_SECTIONS
-- Performing Test C_SUPPORTS_FNO_FUNCTION_SECTIONS - Success
-- Performing Test C_SUPPORTS_FFUNCTION_SECTIONS
-- Performing Test C_SUPPORTS_FFUNCTION_SECTIONS - Success
-- Performing Test CXX_SUPPORTS_FFUNCTION_SECTIONS
-- Performing Test CXX_SUPPORTS_FFUNCTION_SECTIONS - Success
-- Performing Test C_SUPPORTS_FDATA_SECTIONS
-- Performing Test C_SUPPORTS_FDATA_SECTIONS - Success
-- Performing Test CXX_SUPPORTS_FDATA_SECTIONS
-- Performing Test CXX_SUPPORTS_FDATA_SECTIONS - Success
CMake Warning (dev) at /usr/lib/llvm-7/cmake/HandleLLVMOptions.cmake:767 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'LLVM_ENABLE_EH'.
Call Stack (most recent call first):
  CMakeLists.txt:20 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/lib/llvm-7/cmake/HandleLLVMOptions.cmake:768 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'LLVM_ENABLE_RTTI'.
Call Stack (most recent call first):
  CMakeLists.txt:20 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/lib/llvm-7/cmake/HandleLLVMOptions.cmake:847 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'LLVM_EXPORT_SYMBOLS_FOR_PLUGINS'.
Call Stack (most recent call first):
  CMakeLists.txt:20 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- IWYU: configuring for LLVM 7.0.1...
-- Found Git: /usr/bin/git (found version "2.7.4") 
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/include-what-you-use/build
$ make -j8
Scanning dependencies of target include-what-you-use
[  7%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu.cc.o
[ 14%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_ast_util.cc.o
[ 21%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_cache.cc.o
[ 28%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_driver.cc.o
[ 35%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_getopt.cc.o
[ 42%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_globals.cc.o
[ 50%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_include_picker.cc.o
[ 57%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_lexer_utils.cc.o
[ 64%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_location_util.cc.o
[ 71%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_output.cc.o
[ 78%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_path_util.cc.o
[ 85%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_preprocessor.cc.o
[ 92%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu_verrs.cc.o
[100%] Linking CXX executable bin/include-what-you-use
collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
compilation terminated.
CMakeFiles/include-what-you-use.dir/build.make:278: recipe for target 'bin/include-what-you-use' failed
make[2]: *** [bin/include-what-you-use] Error 1
make[2]: *** Deleting file 'bin/include-what-you-use'
CMakeFiles/Makefile2:136: recipe for target 'CMakeFiles/include-what-you-use.dir/all' failed
make[1]: *** [CMakeFiles/include-what-you-use.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by kimgr** [comment]
@peroket No obvious solutions, I'm afraid. Could you be running out of memory? Check your `dmesg` or similar for low-level/system warnings/errors at about this time. I had a machine that would segfault on linking because that was the only time I used enough memory to hit a bad memory circuit.

**Comment by peroket** [comment]
In `dmesg` i have the message:
```
ld[15119]: segfault at 20 ip 00007fdcebd17120 sp 00007ffd1a8acbf0 error 4 in libbfd-2.26.1-system.so[7fdcebc8a000+126000]
Code: 8b 44 24 20 a9 00 00 00 02 74 c7 49 8b 84 24 e0 00 00 00 b9 01 00 00 00 be 01 00 00 00 4c 8b 90 c0 00 00 00 4c 89 d0 0f 1f 00 <8b> 50 20 48 8b 80 e0 00 00 00 48 8b 80 c0 00 00 00 f6 c6 20 0f 44
```

I have to say i'm not that familiar with ubuntu to check all the system stuff.

**Comment by kimgr** [comment]
That doesn't mean anything to me either. Could you try increasing the amount of RAM available to the docker container?

**Comment by mkacperek** [comment]
I had the same issue, I'm working on Ubuntu 16.04 as well. Default ld segfaults, but if you switch to ld.gold (you should have it installed with binutils already) it will show you the actual linking errors. 
Side note: gold is better in many ways (also faster), you can consider switching to it anyway.

For me the problem with iwyu was that it tried to compile and link against different clang/llvm library versions - I still had clang and llvm in versions 5 and 6 installed. Using CMAKE_PREFIX_PATH didn't cover it.

After I removed libclang-6.0 dev, libclang-5.0 dev, llvm-6.0-dev and llvm-5.0-dev I moved on - but it doesn't compile now, seems not to be compatible with clang/llvm 7.0.1... 

Errors for the released 0.11 version:

> In file included from /home/martakacperek/tools/include-what-you-use/iwyu.cc:115:0:
/home/martakacperek/tools/include-what-you-use/iwyu_preprocessor.h:195:8: error: ‘void include_what_you_use::IwyuPreprocessorInfo::InclusionDirective(clang::SourceLocation, const clang::Token&, llvm::StringRef, bool, clang::CharSourceRange, const clang::FileEntry*, llvm::StringRef, llvm::StringRef, const clang::Module*)’ marked ‘override’, but does not override
   void InclusionDirective(clang::SourceLocation hash_loc,

Errors for master:

> [  7%] Building CXX object CMakeFiles/include-what-you-use.dir/iwyu.cc.o
/home/martakacperek/tools/iwyu-exp/include-what-you-use/iwyu.cc: In member function ‘bool include_what_you_use::IwyuBaseAstVisitor<Derived>::VisitCastExpr(clang::CastExpr*)’:
/home/martakacperek/tools/iwyu-exp/include-what-you-use/iwyu.cc:2034:12: error: ‘CK_ZeroToOCLOpaqueType’ is not a member of ‘clang’
       case clang::CK_ZeroToOCLOpaqueType: // OpenCL opaque types are built-in.
            ^
/home/martakacperek/tools/iwyu-exp/include-what-you-use/iwyu.cc:2044:12: error: ‘CK_FixedPointCast’ is not a member of ‘clang’
       case clang::CK_FixedPointCast:
            ^
/home/martakacperek/tools/iwyu-exp/include-what-you-use/iwyu.cc:2045:12: error: ‘CK_FixedPointToBoolean’ is not a member of ‘clang’
       case clang::CK_FixedPointToBoolean:

**Comment by kimgr** [comment]
@mkacperek You're building IWYU against Clang with mismatching branches. See https://github.com/include-what-you-use/include-what-you-use/blob/master/README.md#how-to-build.

The tip about ld.gold is a good one, I also use gold for LLVM dev because it's much much faster.

I'll close this ticket, we have enough infrastructure building IWYU that I'm confident there's nothing we can do to avoid a segfault in @peroket's environment (it does sound like it's low on memory), and the problems cited above are unrelated.

**Comment by Flamefire** [comment]
I ran into the same issue and am pretty sure I'm not building against mismatching branches.

I checked out `clang_7` (0.11) and used the gold linker which shows many errors in `/usr/lib/llvm-7/lib/libclang*` about "invalid section group".

Link command is: `/usr/bin/c++   -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -w -ffunction-sections -fdata-sections -O3 -DNDEBUG  -fuse-ld=gold  -Wl,-O3 -Wl,--gc-sections CMakeFiles/include-what-you-use.dir/iwyu.cc.o CMakeFiles/include-what-you-use.dir/iwyu_ast_util.cc.o CMakeFiles/include-what-you-use.dir/iwyu_cache.cc.o CMakeFiles/include-what-you-use.dir/iwyu_driver.cc.o CMakeFiles/include-what-you-use.dir/iwyu_getopt.cc.o CMakeFiles/include-what-you-use.dir/iwyu_globals.cc.o CMakeFiles/include-what-you-use.dir/iwyu_include_picker.cc.o CMakeFiles/include-what-you-use.dir/iwyu_lexer_utils.cc.o CMakeFiles/include-what-you-use.dir/iwyu_location_util.cc.o CMakeFiles/include-what-you-use.dir/iwyu_output.cc.o CMakeFiles/include-what-you-use.dir/iwyu_path_util.cc.o CMakeFiles/include-what-you-use.dir/iwyu_preprocessor.cc.o CMakeFiles/include-what-you-use.dir/iwyu_verrs.cc.o  -o bin/include-what-you-use -Wl,-rpath,"\$ORIGIN/../lib:/usr/lib/llvm-7/lib" -lpthread /usr/lib/llvm-7/lib/libclangBasic.a /usr/lib/llvm-7/lib/libclangLex.a /usr/lib/llvm-7/lib/libclangAST.a /usr/lib/llvm-7/lib/libclangSema.a /usr/lib/llvm-7/lib/libclangFrontend.a /usr/lib/llvm-7/lib/libclangDriver.a /usr/lib/llvm-7/lib/libclangParse.a /usr/lib/llvm-7/lib/libclangSerialization.a /usr/lib/llvm-7/lib/libclangSema.a /usr/lib/llvm-7/lib/libclangAnalysis.a /usr/lib/llvm-7/lib/libclangEdit.a /usr/lib/llvm-7/lib/libclangAST.a /usr/lib/llvm-7/lib/libclangLex.a /usr/lib/llvm-7/lib/libclangBasic.a /usr/lib/llvm-7/lib/libLLVM-7.so.1 
`

Compile commands look like `/usr/bin/c++  -DIWYU_GIT_REV=\"5658531\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/usr/lib/llvm-7/include  -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -w -ffunction-sections -fdata-sections -O3 -DNDEBUG   -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS  -fno-exceptions -o CMakeFiles/include-what-you-use.dir/iwyu.cc.o -c /home/alex/git/include-what-you-use/iwyu.cc
`

Anything suspicious there?

**Comment by carlosgalvezp** [comment]
Hi,

I'm getting the same error as discussed before. Building as part of a Dockerfile but also manually from an Ubuntu:16.04 image.

-Using version 8 for Clang, LLVM and IWYU. 
-Clang and LLVM installed via apt as suggested in the README.
-Failing both using GCC 5.4 and Clang 8 as compilers.

Linking with gold or ld.gold gives a bunch of these errors:
/usr/bin/ld: error: /usr/lib/llvm-8/lib/libclangBasic.a(XCore.cpp.o): invalid section group 124 refers to earlier section 47

I don't believe it has to do with memory. Could it be that the libraries installed from APT are incompatible? I added the repository with:
`apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main"
`

Thanks!
